### ISSUE TITLE
Error: Could not find or load main class fanx.tools.Fan

### ISSUE THREAD

**Issue by skewty** [fanx-dev/fanIDE#2]
I tried pointing "Fanx Home" path in NetBeans Preferences to `C:\Program Files\fantom-1.0.77` which is my FAN_HOME environment variable location.  Do I need to set another environment variable or something?

```
Error: Could not find or load main class fanx.tools.Fan
Caused by: java.lang.ClassNotFoundException: fanx.tools.Fan
```

**Comment by chunquedong** [comment]
Sorry for that. It couldn't work with Fantom runtime.
